apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: ilhemb/flask:v14
        env:
          - name: PYTHONUNBUFFERED
            value: '1'
          - name: PYTHONIOENCODING
            value: 'UTF-8'
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      role: main
  template:
    metadata:
      labels:
        app: postgres
        role: main
    spec:
      containers:
        - name: postgres-main
          image: postgres
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: mysecretpassword              
            - name: POSTGRES_DB
              value: todolist_db
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-replicas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      role: replica
  template:
    metadata:
      labels:
        app: postgres
        role: replica
    spec:
      containers:
        - name: postgres-replica
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: mysecretpassword          
            - name: POSTGRES_MASTER_SERVICE_HOST
              value: postgres-main
            - name: POSTGRES_MASTER_SERVICE_PORT
              value: "5432"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
  clusterIP: 10.43.92.150
  